---
samples: "samplesheet.csv"
fastq_dir: "/mnt/data0/noah/testing/test_data"

ChromNoPatch: "/mnt/data0/fdb/igenome/Homo_sapiens/Ensembl/GRCh37.75/Annotation/Genes/ChromNoPatch.bed" 
gtf: "/mnt/data0/fdb/igenome/Homo_sapiens/Ensembl/GRCh37.75/Annotation/Genes/Homo_sapiens_GRCh37_75.gtf"
chromSizes: "/mnt/data0/noah/refs/GRCh38/Annotation/Genes/ChromSizes_hg38_ordered.txt"
starIndex: "/mnt/data0/apps/pipelines/STAR/index/hg19"

picard_path: "/mnt/data0/apps/picard/build/libs/"
