---
sampleSheet: "samplesheet.csv" 

ChromNoPatch: "/mnt/data0/noah/refs/GRCh38/Annotation/Genes/ChromNoPatch.bed" #Fixed for argonauts - bed-style chromosome size file
chromSizes: "/mnt/data0/noah/refs/GRCh38/Annotation/Genes/ChromSizes_hg38_02.txt"
blacklist: "/mnt/data0/noah/refs/GRCh38/Annotation/blackList/hg38-blacklist.v2.bed"

significance_value: "FDR" #'FDR' or 'PVALUE'
FDR_threshold: 1e-5
PVAL_threshold: 0.01
