---
samples: "samplesheet.csv"

starIndex: "/mnt/data0/noah/refs/GRCh38/Annotation/STAR_index"
ChromNoPatch: "/mnt/data0/noah/refs/GRCh38/Annotation/Genes/ChromNoPatch.bed"
gtf: "/mnt/data0/noah/refs/GRCh38/Annotation/Genes/genes.gtf"
chromSizes: "/mnt/data0/noah/refs/GRCh38/Annotation/Genes/ChromSizes_hg38_02.txt"

picard_path: "/mnt/data0/apps/picard/build/libs/"
